export const FETCH_RACES              = 'FETCH_RACES'
export const FETCH_RACES_PENDING      = 'FETCH_RACES_PENDING'
export const FETCH_RACES_REJECTED     = 'FETCH_RACES_REJECTED'
export const FETCH_RACES_FULFILLED    = 'FETCH_RACES_FULFILLED'
